name = "fayu-worker"
main = "src/index.ts"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "fayu"
database_id = "63e25b3d-e95f-4c3b-9f94-53daee7c5631"